name: Publishing to Maven Packages
#on: [ push ]  # Trigger the workflow when a push (commit) event occurs
on:
  push:
    branches: [fix/DX-563]

env:
  SECRET_KEY: |
    -----BEGIN PGP PRIVATE KEY BLOCK-----

    lQdGBGYOVVoBEADnvv8Ev0H2w2ZpwW5PbHDLhOonSN5MA/WHcTpjTC8Ib1bG3A1q
    VzZlSeBaGxcoxjoBgz0ntg71UXww5OA/Vh2DNL+uFDr1hwYElFuiYXj757n/EioG
    l6wqCwWFPzoCoqHapQAP4340Vcv6zHO16LAtQQigPM1rMWCuYhMPtyau25fFn8w5
    PSvJgsOv7nRj++JUnL3ajqjBJhV82FHaLXfQy2n1UKthwnXSWQaVz+YaHER2RjyW
    25JZGgOs4GS9UqsrltUxj+Kt09jywO/k7dQLNUGHQrBYW/7BLO+bP2Euhz+tIpih
    xRkb6OZYYUCTMSDBNnDm3jR9ZE8hyZ8qYD/aT5XCDlOikYbyc8c7d5o8xo/pcU8p
    2Loz5XU8ejZk60lHPgbC5u/bziWqvcr1jg/aQWXaTOQEOZg3Ip5A51CmLneIc/4u
    dUVcIBdZRSGtAbsYAlxGj78oxuSrNEqlr7Wi+iXb9mbK55jpJaKOi8RzcrRUuXEV
    e/4nQKfzw3D6Gi7plbU75ysoXqFFXFvOx5rMvWn04NS0vvKSft31H+d/jlRDgGrp
    VxdbaG/Is9QW/jfU+4yRzcT9M5h1JxgM3mrmRWBC5Gd9bRZuYZD1mW3L3bSs9syf
    L1fFM5KmtUKdTmcuppOtSmjrlfmogIDiyxtGO6vxrkbM4fgljL+/+60ofQARAQAB
    /gcDAuyz3bzdrtQN9rq5Wu4Lpd2QPF/MWNXRi6GCX4QZMQBXUvWXkYLjqN7SmYk4
    zg6efOOPkw6OiIitHPk8SHtMH3L4algLmvePOMOOj4s+wFViR9nltBw7V7L6ojT5
    QAGdsfHJTr+2yAwrouOWAjYoERig5c6xNN0XltcvJLvZSAeEzebuyOcanjMZaVZF
    INj5h16Ai56qzTT8JrMJRjFkGnXfqjYUJ1smtXXuAu8eHd1vPJpI5d1C8dhckEyH
    Ju9DxWk65/xqjBR2dSIijyzZ3L4fe/hM4Okl4MapmANdVk3/Dj9EGX/xOs/E/OnD
    R9u7hpc7LehERJUR//JbrNhOkloLJEbYEcQQUvMaMGA79dR9JHM834JVQDYqAPgA
    hS+v8VVb1hKPLdEimq5QM4zDVIjjl/FCKakncf+x7+k/FUDAVE6PmVkudFq7isbb
    CjsMnRvnW2xvLHAZ3Ax4iO7rZuphArcAa3MZxWYoyDWT4k1fRsch8XO0zHuj0c4B
    Nonk3VDzPkrV9limb0oRnmoXr5x9cLC5AZbXO5qnar/PPJFI4vcm5PZlOAjUJawH
    odE14zxOeBiOFu4GSY47U31cc/fuIZ01Q79VNPIijWUV9wxwzNX6pGDGRikY8WKL
    GlTYOYYb6kJoV8SWyyQZpEm/Q+SVl2eifVw7hZclZ32lkyu7N5DN/gb0/0XGbAgS
    8gxuLOGeF4IXiKXARcHUMKKdrt7Coh6KudmonRHQZFCjpy+uW8mBu+WfHUoZX8v4
    d3QxY5KZGDtElMl04uvBvtuSJJe0zO2egE1SlqGdhG4RdsVvx/tf0XkKfPpnChH1
    VPCL8zOTj6UIYL+CyERCIjLt/DFOdsOC5Tr6/y/SdSVE1pR+n3oka++gzercehtT
    4u5xbeas4nO2l3KtidtgbLISUepo9urTfF+oNoWikVP+qGQ62adK6WD1UcXZKMfZ
    lTg+8fAuxhA4sdy9q2GShgVdnzRIxK0wybS7b8BaC2qB2iylSRiMPo8KMnmydYyM
    GqeWJhzDiHrEbN4kmxoUs1D/s6UoTVWMS815pzqL1C7j0etDer8x0JAc6DNMCB23
    bRxWOtUpCKTSvqq837E1kQezCzg9r8rDOlxzhYFiZ9TcOXgC/XfjbA+66LrZCL37
    9h0FdJEN7on/R70GLX6bq4s9mZqauBxi1/Bvm4Sf/B0KDOFI4XtP6Axt6flwLPL5
    xHWDxAC00fjqrc5r9kjhDMljy7QgUxgmEJBBig3ZQ5K5QO5k6hHRQae2bFCd46se
    qYRBdD05mMnV+pSUobk6Vzde9Qov5ABVvnQjJe2RIAwSs6AfA/+IEAnk4IasA1Im
    Vyk/4SYMojxQV1LZYCBBDsRJ/D6+RgosC8Y1bvSm+VmuYBpgXWXHyUhczyxfn0ci
    WDjSRZ4a8uL4s9rIhiClAugZtZFeULELFuERz3xg5sevt6h+zvzRXghPeK5hztRW
    fmH4JoR+IqEYfRFI0tLcnM4P6x9PfrHSBLUa2dzuRux55kPgVe/Q7AGsfxq8tuPy
    BbvjNuNTnBME8K8S9tVIQK8SEbTfkDb94+VsVMHes+UiPe+zQACY9H6EDbBxIIAq
    B8YgpWzWN1Sk5/TZ8YiBIn8lxBeZuhArA7Rv0wNI28Ky0EPc7JTYDN24jppHUk05
    M7PvhrOSLpS5N53/AspKsHjFqqmlgK7LN1mu+avUh90bIzR38JNTBVrPs+pheYAk
    M+DujhlwMTWJF0Pkn8tylSNg0tsv+XdbSVg07TwoRtRsQQYz+8PdPkO0JkNvbnRl
    bnRzdGFjayA8bW9iaWxlQGNvbnRlbnRzdGFjay5jb20+iQJUBBMBCAA+FiEEVuK5
    dvQ3o7en34bNCfUtYZN0CYgFAmYOVVoCGwMFCQeGH1oFCwkIBwIGFQoJCAsCBBYC
    AwECHgECF4AACgkQCfUtYZN0CYiEdBAAq7rXuBpKIfksZxum7kVNoOcOR9gdFxvh
    jMmDi2+ikHfm2kwKl38dbSXYlgH+pkwtgrHalZT9+zXhmIdzwCj0uUG0qNLr74QE
    PHpRmuWMrBoV9RbPXPF1jezP9Aml4baDg7sVf0g56EmRufYPQjNSkRTM+JPsz3LK
    wl4jkquk0NjunT26+caoR5RrZnox25B3jklLQ4H1gcTEYZUWqbK2qMylHhCpsups
    R0WoZZsSKephYZuFXXlU/1/KK7496YvYP8jCytr+pd9E2EYv9uKgd5wZsQizflDY
    NvYGxY1m8ceTdA8WPkLlr5oGR0uMZiHciuqceqmR92XDqXKzcZcyo9PBKSDzproh
    YHYCQxRq/IxOcec1htXeBEVPAoWF19ValnA/2CJ+HCxOyY++bBaZN7lIWGeekRuW
    mXd77MB1prhaSzlTLNMU0aIjjkQvlGnc5+luTmsI252LSLfhDmozjDM2uf7Wbmmh
    FNKPkrZbNKDyFsZwnEi6okzk+2PThyVjxn9B+WSXdp6YfoO0ppeKoxlisHpI3UHq
    udMj6kzu3OrqNsgwlNUSgxMGCjBiJTIMkn56VSrDJPEOxUfL55pTnhK3mtXf41FO
    gpH4sElD6jOBsylQgO6WxtxlvjkqAYmVO0ONOiVPE8WNxrjhhQUDAHDC/u97mFF3
    oCUXZZTqlaSdB0YEZg5VWgEQAKIldxSfjpblfbY4CVhGINz+oLGsBLrtQQPdIng1
    RkWTiw42apytLNc3KSgx9bVwEXV5rISYjfXxnJuJ86JCDRfHhMRjFH1UbAfyUcMK
    3rtltuxLNMUu5jLwIpkf/SB9gOvRsQ0+/+YpaGN5AUxCfhzUGY/fjXqFNsR1Yc7Z
    A5xwDwiXT/000g8/AbxP1U+h/fwr6yrZsBuOtGGD15QxNxg8zf4Q7fd/F6fJftCd
    PGWkHNIzMbBGYUEq56/XZoCoZ2jQSGGe3ZXER0epaxPCHglwBeF6BW7RNqGLURBg
    LXBGEJpHPSJ/hXcWLQUaoutgql1qD8/q9WzawcTOxxuCjfRtfrILWlFFGnDP5v4o
    690TFrIl2NbAkGS34q9uBZmnBVpGgx+G/MacBXxHzmtNs2h5RjFDZmj/p3V7AUPo
    btdEF+n8X4biNgHjBcq8ypMwfnuJ2JTt1F2I37QELwS6kaPTVlVt9JUvy9QJrQAf
    2NcogwLxg4sGIbLECDiYMUiEItBa8Mbh/+wKWWpuHWjOYePozWi0zeWDWpkdSohu
    TaZ9LmNHQEXd6X34F+5vSxXZU0+o98bMfmkmqNvYfcqsa6QOKsmfq/occjx6miwm
    oHCpIpW59BkD5Q5FqfxqYxlb/74dbylDXHwloANq3zNKw4V4rTkWgZQo5eOCgdDS
    n/XlABEBAAH+BwMCef2OLTGMPcT2HfvR082mgBYdD7ORopPU0PAkayEsFMOvYMpg
    4lQ+FyH+E9hXxMFTmS55n3OBkZ5+kgCKuGQWQcJs+OY8wKdJomMLqN9KmCOx0UZb
    tfbTAAKsrspN9F6WPIapLZCOirEVJsheCU5W/m7pbrfL1ObCEff5OwE6eHpeAmGL
    HL3rdPuYxcwlEkFN7CbmDbpFGNLYYF11zmextWXQiqbqcK2m0pL/Q0mvKW41dFbV
    zsEV1ydWYM8xKHpwp0xbikJi0mS3xWF0ydhwVhrQbkaVjlaXFyrTgvTtI1NJ2Bio
    8s3zFFAgLqvcAFxzR5CGw61B7Fm3Nb/0ruPBNxTrnlpEUQqUJ8VGnOnJHcD7PPRC
    WaQx34gpTbDhWrgYLwXJsggaNRvfQEw8OxQEg9Ksn4HdbzJ8AaXHJ38WZkAj7cVN
    wetKq+T7/qQbJx9R6OBMSF88j9Q6r6VBWyqFrx7pavbyirfUg6mTupGN9a4QTyQ4
    na/9kYhnOpQWiy+iH9X+NdA8Vfz58kpaN+V1LyIBGjtk7oPpyNQSaU5bE8oxbt0l
    /WiiHKd3TeFyFYqHF3JFY9s4v4SXyeY2RO+7i8kgRFinOWSJ4joCnVJ5Xx3qvTUo
    DqDHRUWBoNhrKNKxpjw1MN3CdN7/wf8vT6aKFySGWfZUzKoAzUY1+Qw8SV3fFT/S
    F6FyE6cxvbjHEMmm4lbrLwc6tSmJ3XXetnXkEegiHUBMU9FbD9PPye+0AYNxkK7V
    v0x2s+fkMtjcuHtEwrCHEwbwva9qOkPH7wMV26Ch0mVEfDsUqlY4tFPL9pksAbuw
    VKjITVLJfiBJSIlrGe/qL0QbOPmubqbXFpk116OCG3ca96U19zuI0i+qUFrqp73w
    3ZPIbCG07L0qtMFZOh9gnmwav0i6PTL7BBnNWKzGrnGCBLLvUhWDwcLtDplUcCeS
    lLsxNgCLf4zf5YjK1RTd7lQ+iCSG/AgMWVPpsrt54Fg1hc+g+1E5leD+Aj+y1A/H
    FDTx9LqMV1wYGKOwSFlCKU890qsED9NFi0ESPpaBado4/HFEGkQ1TxXX0EHeGOfi
    4TQlcWdW0vMZZY+227S4XcAmTe0vSgeDuwX0E06re0mtWGHlBionss/1wJnAo1vq
    FhaZor7EiuYbVR+J1zuxgMfRGVjy3nk6PUvzW2GbmwlQCfzelIDTgzX9BuxywAyp
    JAcMxunBKospxBED1fw/o+rzAMcYuBGjSfZ4lmG15gYtrseoFuw676fHGqGbKhDQ
    4CsFexwCOH2vFYVGZYsOIpRLkXurMfEs223pvboFKO/J8AOaTOgdsxGCPmyUD9MV
    Vf1n11QIPafeSoeARzAztMNITl/SjtjQak0HEPy3unOaf+Fd+UtIOn77K+ElcfN4
    W5J1dqGEFRKnRZLVfNjWITUDGvd7vDqCyLxYZD/hxpD44nc8qPzFMv81B/MS8dat
    Ihf9fotCpUnDuQo2S1fWkZJbSOJh/MWic0OA8+znUNcbpyiNCWct0+dLlvoW1TF3
    LOl/819a5yLOgGPr0aK0j62LxaABBAw9o2QiIP1M2KHBsD01WFau+t8Ly3XsspVy
    HXH8tuE0JakQidU4F0B+PrJAUpQbDJW9Kyk2N5JxSb2HRERSlWCccRA8XMDDaP0v
    C5UPMrVKXV7aO6BNsP1xSZxhVIbnG54JAWLiAy6HGRY2iBPjqkjL0LEfFekt8T2K
    REJFwq2oXqAfGfCbWGk7nlvLhwEq+6ZezJ1KSWiJswD16mwd/khFtfDh6odcHBI1
    hYkCPAQYAQgAJhYhBFbiuXb0N6O3p9+GzQn1LWGTdAmIBQJmDlVaAhsMBQkHhh9a
    AAoJEAn1LWGTdAmIX8IP/2Y2vpLGqqVRARbczuYNJ2Qu1eVGdFiCS8NaWFFRFTRp
    JOdotS8C2C78Yq83JEawPbjq+MKXZK0gtol3pSLkWNJh746UKH34dmLqnwEm5cHZ
    QfyzCBAr+swFrKd9TWszV7JS4FW54xzLIZGQOpJInrUNI8JlBsm/EuJEHxYaZVpG
    B8Ozss/cu10gFM67aT/XN67TReYuLF8l8HGXknsr+cbrA8QK/2BHD2NqY4M0/QAy
    482n0qvhW6UlGWROxqqYoGUhJ2QvCw/qXuAvQloe0xOCjRT0EgjnvvrGQJlhXk7u
    jVblI5V08xdOGVCNQB8dXo/KT5vJydOBa1uDDwti0sC2zKZqaQKbUiZlxJrukIq0
    1Kt39oqbe9pYE6E/HB9UtzN4+wx335m2HDnnHS39CM0HFAZZZQemyAWODBCHWjb6
    5SGcTGm6H/lKrvUcGdP64NtbNsWXEbv+xzEL0ouczkzEXjjJMilifjPOb8TR2Ik/
    x4SHKeYOPbQ/2FAPgAnp2+IXcKrGZ37MKRkSUzZUCP0L85E5askidXzYe6OCektx
    X4ZMMNKAh9kGGJofWBBfvHXi6mAXCS8scn9l6PbgvocvRmEeddwRZSHm2ADX4P9N
    3mMjWwpOcmN9aEX0VfkwPfXpIgdikWWYUT93b9uDwfgaK1QR5bqsixCqSCKfTw6Z
    =j06H
    -----END PGP PRIVATE KEY BLOCK-----

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Install gpg secret key
        id: install-secret-key
        run: |
          # Install gpg secret key
          cat <(echo -e $SECRET_KEY) | gpg --batch --import
          # Verify gpg secret key
          gpg --list-secret-keys --keyid-format LONG
      - uses: actions/checkout@v3
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE
      - name: Publish to Maven Central Repository
        run: mvn --batch-mode -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

#        run: mvn --batch-mode deploy
